modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="Zillion - Kamen Rider Gazer Zero"
description='''Kamen Rider Gazer Zero armor, Zillion Driver and henshin effects.'''
[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[21.1.0,)"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="geckolib"
type="required"
versionRange="[4.7,)"
ordering="AFTER"
side="BOTH"
[[dependencies.${mod_id}]]
modId="playeranimator"
type="required"
versionRange="[2.0,)"
ordering="AFTER"
side="CLIENT"
[[dependencies.${mod_id}]]
modId="bendylib"
type="required"
versionRange="[4.0,)"
ordering="AFTER"
side="CLIENT"
